# Generated by Django 4.2.3 on 2024-01-10 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BitacoraActividad',
            fields=[
                ('bit_id', models.AutoField(primary_key=True, serialize=False)),
                ('bit_descripcionactividad', models.TextField(blank=True, null=True)),
                ('bit_fechahoraactividaddia', models.IntegerField(blank=True, null=True)),
                ('bit_fechahoraactividadmes', models.IntegerField(blank=True, null=True)),
                ('bit_fechahoraactividadanio', models.IntegerField(blank=True, null=True)),
                ('bit_estadoregistro', models.CharField(blank=True, max_length=1, null=True)),
            ],
            options={
                'db_table': 'bitacora_actividad',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Contrato',
            fields=[
                ('con_id', models.AutoField(primary_key=True, serialize=False)),
                ('con_fechainiciodia', models.IntegerField(blank=True, null=True)),
                ('con_fechainiciomes', models.IntegerField(blank=True, null=True)),
                ('con_fechainicioanio', models.IntegerField(blank=True, null=True)),
                ('con_fechavencdia', models.IntegerField(blank=True, null=True)),
                ('con_fechavencmes', models.IntegerField(blank=True, null=True)),
                ('con_fechavencanio', models.IntegerField(blank=True, null=True)),
                ('con_tipocontrato', models.CharField(blank=True, max_length=100, null=True)),
                ('con_estadoregistro', models.CharField(blank=True, max_length=1, null=True)),
            ],
            options={
                'db_table': 'contrato',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MaeCliente',
            fields=[
                ('cli_id', models.AutoField(primary_key=True, serialize=False)),
                ('cli_nombreempresa', models.CharField(blank=True, max_length=255, null=True)),
                ('cli_infocontacto', models.CharField(blank=True, max_length=255, null=True)),
                ('cli_estadoregistro', models.CharField(blank=True, max_length=1, null=True)),
            ],
            options={
                'db_table': 'mae_cliente',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ReqMantenimiento',
            fields=[
                ('req_id', models.AutoField(primary_key=True, serialize=False)),
                ('req_descripcion', models.TextField(blank=True, null=True)),
                ('req_fechasolicituddia', models.IntegerField(blank=True, null=True)),
                ('req_fechasolicitudmes', models.IntegerField(blank=True, null=True)),
                ('req_fechasolicitudanio', models.IntegerField(blank=True, null=True)),
                ('req_estado', models.CharField(blank=True, max_length=100, null=True)),
                ('req_estadoregistro', models.CharField(blank=True, max_length=1, null=True)),
            ],
            options={
                'db_table': 'req_mantenimiento',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RolUsuario',
            fields=[
                ('rol_id', models.AutoField(primary_key=True, serialize=False)),
                ('rol_nombrerol', models.CharField(blank=True, max_length=100, null=True)),
                ('rol_descripcion', models.TextField(blank=True, null=True)),
                ('rol_estadoregistro', models.CharField(blank=True, max_length=1, null=True)),
            ],
            options={
                'db_table': 'rol_usuario',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('usr_id', models.AutoField(primary_key=True, serialize=False)),
                ('usr_nombreusuario', models.CharField(blank=True, max_length=100, null=True)),
                ('usr_contrasenaencriptada' ,models.CharField(max_length=255, blank=True, null=True)),
                ('usr_estadoregistro', models.CharField(blank=True, max_length=1, null=True)),
            ],
            options={
                'db_table': 'usuario',
                'managed': False,
            },
        ),
    ]
