# Generated by Django 4.2.3 on 2024-01-10 20:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('solucionesMovilesApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usuario',
            options={},
        ),
    ]
