# Generated by Django 4.2.3 on 2024-01-10 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solucionesMovilesApp', '0003_usuario_rolusuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='usr_apellidousuario',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='usr_celular',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='usr_dni',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
    ]
